# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NV6qvFji6-6YUyE25MsBb8d-WowP06mk
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)
# %matplotlib inline

from google.colab import files
files.upload()

df = pd.read_csv('phq_all_final.csv')
df

df1 = df.head(10)

df1.plot(kind='line',x='score',y='patient_id',color='red')
plt.show()

?